[package]
name = "underway"
description = "⏳ Distributed task queue over Postgres"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
chrono = "0.4.38"
chrono-tz = { version = "0.10.0", features = ["serde"] }
cron = "0.12.1"
jiff = { version = "0.1.13", features = ["serde"] }
serde = "1.0.210"
serde_json = "1.0.128"
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }
ulid = { version = "1.1.3", features = ["serde", "uuid"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }

[dev-dependencies]
futures = "0.3.30"
