name: underway

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: underway
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d remotejobs"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_data:
